//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPojo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowScheme
    {
        public string Id { get; set; }
        public string SchemeCode { get; set; }
        public string SchemeName { get; set; }
        public string SchemeType { get; set; }
        public string SchemeVersion { get; set; }
        public string SchemeCanUser { get; set; }
        public string SchemeContent { get; set; }
        public string FrmId { get; set; }
        public int FrmType { get; set; }
        public int AuthorizeType { get; set; }
        public int SortCode { get; set; }
        public int DeleteMark { get; set; }
        public int Disabled { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
