//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPojo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Fields { get; set; }
        public string ContentData { get; set; }
        public string ContentParse { get; set; }
        public string Content { get; set; }
        public int SortCode { get; set; }
        public int Delete { get; set; }
        public string DbName { get; set; }
        public int Enabled { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
