//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPojo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relevance
    {
        public string Id { get; set; }
        public string Description { get; set; }
        public string Key { get; set; }
        public int Status { get; set; }
        public System.DateTime OperateTime { get; set; }
        public string OperatorId { get; set; }
        public string FirstId { get; set; }
        public string SecondId { get; set; }
    }
}
