//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPojo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public string Id { get; set; }
        public string data_1 { get; set; }
        public string data_2 { get; set; }
        public string data_3 { get; set; }
        public int checkboxs_0 { get; set; }
        public string data_7 { get; set; }
        public string data_8 { get; set; }
        public string data_9 { get; set; }
        public string data_10 { get; set; }
        public string data_11 { get; set; }
    }
}
